### PR TITLE
convert to sym value from session #21

### PR DESCRIPTION
**Pull request by afdev82**
In this way we are sure that we obtain always a symbol from the cookie. 
I don't know how to change the test, I thought we could set the cookie to a valid string value ('world') instead of :default

### CODE REVIEW

**Comment by n0nick** [comment]
1. I'm not sure why casting to a symbol is necessary - could you give me an example for how this affects your use-case and/or what you would like to do with symbols?
2. The tests fail because you are introducing a dependency on ActiveSupport's `#try`, but GeoRedirect does not assume the availability of ActiveSupport (i.e. for non-Rails Rack apps, etc). So, please change your logic to cast to a symbol without using `try`.
3. After that, the tests should behave the same, but I would introduce another tests to make sure that values are always returned as symbols.

**Comment by afdev82** [comment]
Hi, thanks for the reply. 
Yes, I will change to not use "try" for the conversion.
I use the gem in a Rails 4.2+ app and it seems that Rails casts the value in the cookie to be "string" instead of symbol.
When the code checks if the config contains the host that we have in the session (see [here](https://github.com/wazeHQ/geo_redirect/blob/master/lib/geo_redirect/middleware.rb#L42)), it will return always false, because it checks against symbols, but in the variable we have always (in my case) a string.
I thought the best thing (if you want to use symbols as keys in the configuration file) is to convert always to symbols.

**Comment by n0nick** [comment]
OK, that's a good-enough reason to cast. Although I must say, I'm using the gem in a Rails 4.2.3 app and have not experienced such issue.

**Comment by afdev82** [comment]
Strange, but I could investigate further. The version I'm using is the 4.2.5

**Comment by n0nick** [comment]
I'll happily merge a patch that fixes the session values casting to symbols.
If that solves your issue, it might point to one of many possible differences between our apps :)

**Comment by afdev82** [comment]
@n0nick do you know how could I build locally instead of committing and check in travis ci ?

**Comment by n0nick** [comment]
well, cloning, `bundle install` and `bundle exec rspec spec` should do the trick.

**Comment by afdev82** [comment]
Thanks ;)

**Comment by n0nick** [comment]
and now it's up in version [0.5.1](https://rubygems.org/gems/geo_redirect/versions/0.5.1)

**Pull request merged**
