### PR TITLE
add redirect_later config option to choose to redirect future requests after skip

### PR DESCRIPTION
**Pull request by afdev82**

### CODE REVIEW

**Comment by afdev82** [comment]
I don't know if it's fine for you, usually I prefer to use more variables and have more lines, instead of grouping too much to save few lines.

**Comment by n0nick** [comment]
Thanks so much @afdev82 for the work :)
I'm sorry if I'm being difficult but I'm still unsure exactly what this option adds. Code changes look good but I'm having a hard time following the flow (might be because I haven't worked on this gem for a while ;).

Can you explain in your own words what happens when the flag is `false` and the user visits a page?
1. What happens when a normal path `/page` is visited with no flag?
1. What happens when `/page?skip_geo=true` is visited?
2. What happens one request later?

In particular, what's the difference between
* having `redirect_later=false` and visiting `?skip_geo=true`
* visiting `?redirect=1`

**Comment by n0nick** [comment]
Just to clarify, I realize that some of the original features (such as the `?redirect=1` flag) are not well-documented or well-designed, which might add to the confusion here.

**Comment by afdev82** [comment]
In our project we set up the gem to only redirect the homepage: at the moment, when a first time visitor visits other pages, the gem skips the redirection, but then if the user visits the homepage, he's redirected.
We wanted to avoid that, because if I'm in one website, I should stay there (at least in our project).
For that reason, the option `redirect_later: false` stores the cookie with the current host (as usual when redirecting), in this way the future requests will not be redirected.
The option just affects the behaviour of the gem when the redirection is skipped (with option include/exclude or the skip_geo param) and then I request a page that should be redirected.
To answer your questions:
1. The gem behaves as usual
2. The gem will skip the redirection and remember the host for future requests
3. The gem will not redirect the visitor

The only difference is that in the first case the gem remembers the host when skip the redirection, in the second it remembers the host when I visit a page with the `redirect` param.
I know that we could get the same result appending the param `redirect=1` to the query string when requesting the homepage, but the homepage is accessed in many parts of the application and it didn't seem an elegant solution (and in general it should be valid for all pages that we redirect for first-time visitors).
I thought the best solution was to add an option to decide if we want to redirect future requests also when skipping the redirection, because then the visitor is in one specific host and we don't want to redirect him anymore (in general for other pages than the homepage too).

**Comment by afdev82** [comment]
Sorry, but I don't know how to fix the rubocop complaints without changing the rubocop configuration.

**Comment by n0nick** [comment]
OK, thanks for explaining :)
That's OK re Rubocop, I'll pull your change and do the merge manually.

**Comment by n0nick** [comment]
OK, for clarity's sake (I don't like flags which default to `false`), I renamed the flag to `remember_when_skipping`. It allows for your expected behavior when its value is set to `true`.

**Pull request closed without merging**
